export const FIELDS_LIST_ADD_ITEM = "FIELDS_LIST_ADD_ITEM";
export const FIELDS_LIST_EDIT_ITEM = "FIELDS_LIST_EDIT_ITEM";
export const FIELDS_LIST_REMOVE_ITEM = "FIELDS_LIST_REMOVE_ITEM";
export const FIELDS_LIST_TOGGLE_REQUIRED_ITEM = "FIELDS_LIST_TOGGLE_REQUIRED_ITEM";
export const FIELDS_RESTORE = 'FIELDS_RESTORE';


export const INPUT = 'INPUT';
export const TEXTAREA = 'TEXTAREA';
export const CHECKBOX = 'CHECKBOX';
export const RADIO = 'RADIO';
export const SELECT = 'SELECT';
export const UPLOAD = 'UPLOAD';

export const FORM_DESCRIPTION_UPDATE = 'FORM_DESCRIPTION_UPDATE';
export const FORM_ERROR_ADD = 'FORM_ERROR_ADD';
export const FORM_RESTORE = 'FORM_RESTORE';
export const FIELDS_REORDER = 'FIELDS_REORDER';
